# Generated by Django 5.0.4 on 2026-03-15 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('product_id', models.CharField(db_index=True, help_text='Human-readable product code e.g. PROD-001', max_length=50, unique=True)),
                ('available_stocks', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, help_text='Tax as percentage e.g. 18.00 for 18%', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['product_id'], name='products_pr_product_9f5899_idx'), models.Index(fields=['is_active', 'available_stocks'], name='products_pr_is_acti_1bbd74_idx')],
            },
        ),
    ]
